# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class ProfileMaster(models.Model):
    profile_id = models.AutoField(primary_key=True)
    client = models.ForeignKey('ClientMaster', models.DO_NOTHING, blank=True, null=True)
    userid_del = models.IntegerField(blank=True, null=True)
    co_name = models.CharField(max_length=100, blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    pincode = models.CharField(max_length=20, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=80, blank=True, null=True)
    country_code = models.CharField(max_length=2, blank=True, null=True)
    phone_no = models.CharField(max_length=100, blank=True, null=True)
    fax_no = models.CharField(max_length=100, blank=True, null=True)
    email_bak = models.CharField(max_length=100, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    co_branches = models.CharField(max_length=100, blank=True, null=True)
    estd = models.SmallIntegerField(blank=True, null=True)
    staff = models.IntegerField(blank=True, null=True)
    prod_exp = models.TextField(blank=True, null=True)
    prod_imp = models.TextField(blank=True, null=True)
    prod_manu = models.TextField(blank=True, null=True)
    prod_serv = models.TextField(blank=True, null=True)
    ifexporter = models.BooleanField()
    ifimporter = models.BooleanField()
    ifservice = models.BooleanField()
    ifmanu = models.BooleanField()
    bankers = models.CharField(max_length=255, blank=True, null=True)
    imp_exp_code = models.CharField(max_length=100, blank=True, null=True)
    memb_affil = models.CharField(max_length=255, blank=True, null=True)
    std_cert = models.CharField(max_length=255, blank=True, null=True)
    area_id = models.IntegerField(blank=True, null=True)
    annual_turn = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    annual_mult = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    annual_currency = models.CharField(max_length=5, blank=True, null=True)
    exp_turn = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    exp_mult = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    exp_currency = models.CharField(max_length=5, blank=True, null=True)
    imp_turn = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    imp_mult = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    imp_currency = models.CharField(max_length=5, blank=True, null=True)
    creation_date = models.IntegerField(blank=True, null=True)
    profile_status = models.CharField(max_length=10)
    source = models.CharField(max_length=20, blank=True, null=True)
    datasource = models.IntegerField(blank=True, null=True)
    company_id = models.IntegerField(blank=True, null=True)
    eyp_list_id = models.IntegerField(blank=True, null=True)
    iid_list_id = models.IntegerField(blank=True, null=True)
    ip_list_id = models.IntegerField(blank=True, null=True)
    catalog_company_id = models.IntegerField(blank=True, null=True)
    extra_attributes = models.BooleanField()
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    verified = models.BooleanField(blank=True, null=True)
    moderated = models.BooleanField(blank=True, null=True)
    junk = models.BooleanField(blank=True, null=True)
    non_business = models.BooleanField(blank=True, null=True)
    eyp = models.BooleanField(blank=True, null=True)
    iid = models.BooleanField(blank=True, null=True)
    ip_buyer = models.BooleanField(blank=True, null=True)
    ip_seller = models.BooleanField(blank=True, null=True)
    service = models.BooleanField(blank=True, null=True)
    air_freight = models.BooleanField(blank=True, null=True)
    ocean_freight = models.BooleanField(blank=True, null=True)
    export_freight = models.BooleanField(blank=True, null=True)
    import_freight = models.BooleanField(blank=True, null=True)
    pccode = models.CharField(max_length=50, blank=True, null=True)
    pacode = models.CharField(max_length=50, blank=True, null=True)
    fccode = models.CharField(max_length=50, blank=True, null=True)
    facode = models.CharField(max_length=50, blank=True, null=True)
    export_category = models.TextField(blank=True, null=True)  # This field type is a guess.
    import_category = models.TextField(blank=True, null=True)  # This field type is a guess.
    serv_category = models.TextField(blank=True, null=True)  # This field type is a guess.
    manu_category = models.TextField(blank=True, null=True)  # This field type is a guess.
    last_updated = models.IntegerField(blank=True, null=True)
    entry_by = models.IntegerField(blank=True, null=True)
    last_updated_by = models.IntegerField(blank=True, null=True)
    jr_phone = models.BooleanField(blank=True, null=True)
    jr_address = models.BooleanField(blank=True, null=True)
    jr_co_name = models.BooleanField(blank=True, null=True)
    jr_junk_profile = models.BooleanField(blank=True, null=True)
    jr_no_product = models.BooleanField(blank=True, null=True)
    cr_report = models.BooleanField(blank=True, null=True)
    last_call_key = models.IntegerField(blank=True, null=True)
    not_interested = models.BooleanField(blank=True, null=True)
    spell_mistake = models.BooleanField(blank=True, null=True)
    not_callable = models.BooleanField(blank=True, null=True)
    last_verified = models.IntegerField()
    has_duplicates = models.BooleanField(blank=True, null=True)
    ifdistributor = models.BooleanField()
    prod_distributor = models.TextField(blank=True, null=True)
    distributor_category = models.TextField(blank=True, null=True)  # This field type is a guess.
    ifsupplier = models.BooleanField()
    prod_supplier = models.TextField(blank=True, null=True)
    supplier_category = models.TextField(blank=True, null=True)  # This field type is a guess.
    iftrader = models.BooleanField()
    prod_trader = models.TextField(blank=True, null=True)
    trader_category = models.TextField(blank=True, null=True)  # This field type is a guess.
    directory_listing = models.BooleanField(blank=True, null=True)
    product_profile_page = models.CharField(max_length=100, blank=True, null=True)
    punchline = models.CharField(max_length=200, blank=True, null=True)
    sell_kw_last_modified = models.IntegerField(blank=True, null=True)
    buy_kw_last_modified = models.IntegerField(blank=True, null=True)
    prev_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    website_working = models.BooleanField(blank=True, null=True)
    mirainform_uniq_id = models.IntegerField(blank=True, null=True)
    website_direct_link = models.BooleanField(blank=True, null=True)
    member_since = models.IntegerField(blank=True, null=True)
    number_check_status = models.CharField(max_length=20, blank=True, null=True)
    number_check_last = models.IntegerField(blank=True, null=True)
    number_check_attempts = models.IntegerField(blank=True, null=True)
    number_check_next_check_due = models.IntegerField(blank=True, null=True)
    number_check_result = models.CharField(max_length=15, blank=True, null=True)
    co_info = models.TextField(blank=True, null=True)
    co_logo = models.TextField(blank=True, null=True)
    number_mask = models.BooleanField(blank=True, null=True)
    auto_verified = models.BooleanField(blank=True, null=True)
    last_auto_verified = models.IntegerField(blank=True, null=True)
    auto_verification_type = models.CharField(max_length=100, blank=True, null=True)
    last_updated_ts = models.IntegerField(blank=True, null=True)
    last_update_comment = models.TextField(blank=True, null=True)
    cms_production_unit_no = models.IntegerField(blank=True, null=True)
    cms_monthly_prod_capacity = models.CharField(max_length=255, blank=True, null=True)
    cms_no_of_engineers = models.IntegerField(blank=True, null=True)
    cms_no_of_designers = models.IntegerField(blank=True, null=True)
    cms_major_clients = models.CharField(max_length=255, blank=True, null=True)
    cms_capital = models.IntegerField(blank=True, null=True)
    cms_capital_currency = models.CharField(max_length=5, blank=True, null=True)
    cms_capital_mul = models.IntegerField(blank=True, null=True)
    cms_export_percentage = models.IntegerField(blank=True, null=True)
    cms_import_percentage = models.IntegerField(blank=True, null=True)
    cms_income_tax_reg_no = models.CharField(max_length=50, blank=True, null=True)
    cms_service_tax_no = models.CharField(max_length=50, blank=True, null=True)
    cms_central_sales_tax_no = models.CharField(max_length=50, blank=True, null=True)
    cms_co_reg_no = models.CharField(max_length=50, blank=True, null=True)
    cms_warehousing_facility = models.BooleanField(blank=True, null=True)
    cms_orig_equipment_manu = models.BooleanField(blank=True, null=True)
    cms_credit_rated = models.BooleanField(blank=True, null=True)
    cms_credit_rated_agency = models.IntegerField(blank=True, null=True)
    paypal_id = models.CharField(max_length=150, blank=True, null=True)
    customer_value = models.IntegerField(blank=True, null=True)
    business_kws = models.TextField(blank=True, null=True)  # This field type is a guess.
    current_contract_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    prev_contract_amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    pincode_id = models.IntegerField(blank=True, null=True)
    gst_no = models.CharField(max_length=20, blank=True, null=True)
    pan_no = models.CharField(max_length=20, blank=True, null=True)
    business_states = models.TextField(blank=True, null=True)  # This field type is a guess.
    exclude_business_cities = models.TextField(blank=True, null=True)  # This field type is a guess.
    moderate_inq = models.BooleanField(blank=True, null=True)
    dialb2b_inq = models.BooleanField(blank=True, null=True)
    primary_business_type = models.CharField(max_length=50, blank=True, null=True)
    primary_business_kws = models.TextField(blank=True, null=True)
    ifwholesaler = models.BooleanField()
    ifretailer = models.BooleanField()
    ifdealer = models.BooleanField()
    iffabricator = models.BooleanField()
    ifproducer = models.BooleanField()
    prod_wholesaler = models.TextField(blank=True, null=True)
    prod_retailer = models.TextField(blank=True, null=True)
    prod_dealer = models.TextField(blank=True, null=True)
    prod_fabricator = models.TextField(blank=True, null=True)
    prod_producer = models.TextField(blank=True, null=True)
    ownership_type = models.CharField(max_length=100, blank=True, null=True)
    billing_address = models.TextField(blank=True, null=True)
    billing_city = models.CharField(max_length=50, blank=True, null=True)
    billing_state = models.CharField(max_length=50, blank=True, null=True)
    billing_pincode = models.IntegerField(blank=True, null=True)
    billing_country_code = models.CharField(max_length=2, blank=True, null=True)
    tan_no = models.CharField(max_length=20, blank=True, null=True)
    include_business_cities = models.TextField(blank=True, null=True)  # This field type is a guess.
    gst_available = models.BooleanField(blank=True, null=True)
    dont_show_send_others = models.BooleanField(blank=True, null=True)
    trading_brand_name = models.CharField(max_length=100, blank=True, null=True)
    manufacturing_brand_name = models.CharField(max_length=100, blank=True, null=True)
    distributed_brand_name = models.CharField(max_length=100, blank=True, null=True)
    inquiry_preference = models.CharField(max_length=100, blank=True, null=True)
    tin_no = models.CharField(max_length=50, blank=True, null=True)
    arn_no = models.CharField(max_length=50, blank=True, null=True)
    cms_shipment_mode = models.CharField(max_length=50, blank=True, null=True)
    cms_production_type = models.CharField(max_length=100, blank=True, null=True)
    cms_infrastructure_size = models.CharField(max_length=100, blank=True, null=True)
    cms_rewards_recognition = models.TextField(blank=True, null=True)
    cms_clients_name = models.CharField(max_length=100, blank=True, null=True)
    initial_co_name = models.TextField(blank=True, null=True)
    cms_payment_mode = models.CharField(max_length=100, blank=True, null=True)
    cms_niche_market = models.CharField(max_length=100, blank=True, null=True)
    cms_tin_no = models.CharField(max_length=100, blank=True, null=True)
    restrict_adding_rfis = models.BooleanField(blank=True, null=True)
    cin_no = models.CharField(max_length=21, blank=True, null=True)
    restrict_automated_rfis = models.BooleanField(blank=True, null=True)
    co_logo_img = models.TextField(blank=True, null=True)
    do_not_automate_rfis = models.BooleanField(blank=True, null=True)
    dnd_ivr = models.BooleanField(blank=True, null=True)
    dnd_instant_connect = models.BooleanField(blank=True, null=True)
    co_name_hi = models.TextField(blank=True, null=True)
    initial_co_name_hi = models.TextField(blank=True, null=True)
    vat_no = models.CharField(max_length=20, blank=True, null=True)
    address_hi = models.TextField(blank=True, null=True)
    co_info_hi = models.TextField(blank=True, null=True)
    state_hi = models.TextField(blank=True, null=True)
    city_hi = models.TextField(blank=True, null=True)
    gsp_lead = models.BooleanField(blank=True, null=True)
    otp_on_email = models.BooleanField(blank=True, null=True)
    include_business_countries = models.TextField(blank=True, null=True)  # This field type is a guess.
    exclude_business_states = models.TextField(blank=True, null=True)  # This field type is a guess.
    international_lead = models.BooleanField(blank=True, null=True)
    exclude_business_countries = models.TextField(blank=True, null=True)  # This field type is a guess.
    fb_automation_flow_controller = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = '"general"."profile_master"'
